// Provider catalogs captured from Foreman 119bb01. Wildcards retain a provider grant boundary; they do not authorize additional scopes.
export const PROVIDER_CATALOG = {
  autumn: {
    critic: [
      "dateToEpochMilliseconds",
      "epochMillisecondsToDate",
      "getCurrentOrganization",
      "getCustomer",
      "getEntity",
      "getPlan",
      "listCustomers",
      "listEntities",
      "listFeatures",
      "listPlans",
    ],
    description:
      "Autumn billing provisioning, read-only: customers, their plans, add-ons, subscriptions and feature balances, the plan and feature catalog, and entities.",
    root: [
      "dateToEpochMilliseconds",
      "epochMillisecondsToDate",
      "getCurrentOrganization",
      "getCustomer",
      "getEntity",
      "getPlan",
      "listCustomers",
      "listEntities",
      "listFeatures",
      "listPlans",
    ],
  },
  axiom: {
    critic: [
      "checkMonitors",
      "exportDashboard",
      "getDashboard",
      "getDatasetFields",
      "getMetricTagValues",
      "getMonitorHistory",
      "getSavedQueries",
      "listDashboards",
      "listDatasets",
      "listMetricTags",
      "listMetrics",
      "listNotifiers",
      "queryDataset",
      "queryMetrics",
      "searchMetrics",
    ],
    description:
      "Axiom observability, read-only: APL queries over production structured logs, datasets, metrics, dashboards, and monitor history.",
    root: [
      "checkMonitors",
      "exportDashboard",
      "getDashboard",
      "getDatasetFields",
      "getMetricTagValues",
      "getMonitorHistory",
      "getSavedQueries",
      "listDashboards",
      "listDatasets",
      "listMetricTags",
      "listMetrics",
      "listNotifiers",
      "queryDataset",
      "queryMetrics",
      "searchMetrics",
    ],
  },
  exa: {
    critic: [],
    description:
      "Exa web search: semantic search, page contents, and deep research over the public web.",
    root: ["*"],
  },
  inngest: {
    critic: [
      "health",
      "get_app",
      "get_apps",
      "get_function",
      "list_functions",
      "get_run",
      "get_run_trace",
      "list_runs",
      "list_function_runs",
      "get_event_runs",
      "list_envs",
      "list_webhooks",
      "query_insights",
      "list_insights_tables",
      "list_insights_event_schemas",
    ],
    description:
      "Inngest background jobs, read-only: environments, functions, events, runs, traces, failure history, and Insights queries.",
    root: [
      "health",
      "get_app",
      "get_apps",
      "get_function",
      "list_functions",
      "get_run",
      "get_run_trace",
      "list_runs",
      "list_function_runs",
      "get_event_runs",
      "list_envs",
      "list_webhooks",
      "query_insights",
      "list_insights_tables",
      "list_insights_event_schemas",
    ],
  },
  intercom: {
    critic: [
      "fetch",
      "get_company",
      "get_contact",
      "get_conversation",
      "list_companies",
      "search",
      "search_contacts",
      "search_conversations",
    ],
    description:
      "Intercom customer support, read-only: conversations, contacts, and companies.",
    root: [
      "fetch",
      "get_company",
      "get_contact",
      "get_conversation",
      "list_companies",
      "search",
      "search_contacts",
      "search_conversations",
    ],
  },
  jam: {
    critic: [
      "analyzeVideo",
      "fetch",
      "getConsoleLogs",
      "getDetails",
      "getFrames",
      "getMetadata",
      "getNetworkRequests",
      "getRecordingLink",
      "getRecordingUrlVerifyLink",
      "getScreenshots",
      "getUserEvents",
      "getVideoTranscript",
      "listFolders",
      "listJams",
      "listMembers",
      "listRecordingLinkJams",
      "listRecordingLinks",
      "listRecordingUrls",
      "search",
    ],
    description:
      "Jam bug reports, read-only: recordings, console logs, network requests, screenshots, user events, and video transcripts.",
    root: [
      "analyzeVideo",
      "fetch",
      "getConsoleLogs",
      "getDetails",
      "getFrames",
      "getMetadata",
      "getNetworkRequests",
      "getRecordingLink",
      "getRecordingUrlVerifyLink",
      "getScreenshots",
      "getUserEvents",
      "getVideoTranscript",
      "listFolders",
      "listJams",
      "listMembers",
      "listRecordingLinkJams",
      "listRecordingLinks",
      "listRecordingUrls",
      "search",
    ],
  },
  linear: {
    critic: [
      "get_issue",
      "list_issues",
      "list_comments",
      "list_issue_labels",
      "get_document",
      "list_documents",
    ],
    description: "Linear workspace: issues, projects, cycles, and comments.",
    root: ["*"],
  },
  lucent: {
    critic: ["list_issues", "get_issue", "list_insights"],
    description:
      "Lucent session replay, read-only: user-hit issues and periodic session insights.",
    root: ["list_issues", "get_issue", "list_insights"],
  },
  modem: {
    critic: ["search_modem"],
    description:
      "Modem customer feedback, read-only: natural-language search over feedback, topics, people, and companies.",
    root: ["search_modem"],
  },
  neon: {
    critic: [
      "list_projects",
      "describe_project",
      "list_organizations",
      "describe_branch",
      "list_branch_computes",
      "compare_database_schema",
      "run_sql",
      "run_sql_transaction",
      "get_database_tables",
      "describe_table_schema",
      "list_slow_queries",
      "explain_sql_statement",
      "inspect_database",
      "query_logs",
      "list_log_fields",
      "list_log_field_values",
    ],
    description:
      "Other Neon Postgres databases, read-only: projects, branches, schema, read queries, slow queries, explain plans, and logs. Unrelated to Foreman's investigation memory and never the PlanetScale production/customer database.",
    root: [
      "list_projects",
      "describe_project",
      "list_organizations",
      "describe_branch",
      "list_branch_computes",
      "compare_database_schema",
      "run_sql",
      "run_sql_transaction",
      "get_database_tables",
      "describe_table_schema",
      "list_slow_queries",
      "explain_sql_statement",
      "inspect_database",
      "query_logs",
      "list_log_fields",
      "list_log_field_values",
    ],
  },
  openrouter: {
    critic: [],
    description:
      "OpenRouter model intelligence: model catalog, provider capabilities, pricing, benchmarks, usage rankings, account credit, and documentation. Test inference is attended-only because it incurs spend.",
    root: [
      "list-models",
      "get-model",
      "list-model-endpoints",
      "list-benchmarks",
      "list-daily-model-rankings",
      "get-generation",
      "search-docs",
      "get-credits",
      "list-providers",
      "list-app-rankings",
      "send-message",
    ],
  },
  planetscale: {
    critic: [
      "planetscale_list_organizations",
      "planetscale_get_organization",
      "planetscale_list_databases",
      "planetscale_get_database",
      "planetscale_list_branches",
      "planetscale_get_branch",
      "planetscale_get_insights",
      "planetscale_list_schema_recommendations",
      "planetscale_search_documentation",
    ],
    description:
      "PlanetScale production/customer Postgres, read-only: organizations, databases, branches, and query Insights. It is current production evidence, never investigation memory.",
    root: [
      "planetscale_list_organizations",
      "planetscale_get_organization",
      "planetscale_list_databases",
      "planetscale_get_database",
      "planetscale_list_branches",
      "planetscale_get_branch",
      "planetscale_get_insights",
      "planetscale_list_schema_recommendations",
      "planetscale_search_documentation",
    ],
  },
  posthog: {
    critic: ["*"],
    description:
      "PostHog product analytics, read-only: events, insights, funnels, session recordings, error tracking, feature flags, and experiments.",
    root: ["*"],
  },
  resend: {
    critic: [
      "get-automation",
      "get-automation-runs",
      "get-broadcast",
      "get-contact",
      "get-contact-import",
      "get-contact-property",
      "get-domain",
      "get-domain-claim",
      "get-email",
      "get-log",
      "get-received-email",
      "get-received-email-attachment",
      "get-segment",
      "get-sent-email-attachment",
      "get-suppression",
      "get-template",
      "get-tiptap-json-content",
      "get-topic",
      "get-webhook",
      "list-api-keys",
      "list-broadcasts",
      "list-contact-imports",
      "list-contact-properties",
      "list-contact-segments",
      "list-contact-topics",
      "list-contacts",
      "list-domains",
      "list-emails",
      "list-logs",
      "list-oauth-grants",
      "list-received-email-attachments",
      "list-received-emails",
      "list-segments",
      "list-sent-email-attachments",
      "list-suppressions",
      "list-templates",
      "list-topics",
      "list-webhooks",
    ],
    description:
      "Resend email, read-only: delivery status, logs, domains, contacts, segments, broadcasts, templates, and suppressions.",
    root: [
      "get-automation",
      "get-automation-runs",
      "get-broadcast",
      "get-contact",
      "get-contact-import",
      "get-contact-property",
      "get-domain",
      "get-domain-claim",
      "get-email",
      "get-log",
      "get-received-email",
      "get-received-email-attachment",
      "get-segment",
      "get-sent-email-attachment",
      "get-suppression",
      "get-template",
      "get-tiptap-json-content",
      "get-topic",
      "get-webhook",
      "list-api-keys",
      "list-broadcasts",
      "list-contact-imports",
      "list-contact-properties",
      "list-contact-segments",
      "list-contact-topics",
      "list-contacts",
      "list-domains",
      "list-emails",
      "list-logs",
      "list-oauth-grants",
      "list-received-email-attachments",
      "list-received-emails",
      "list-segments",
      "list-sent-email-attachments",
      "list-suppressions",
      "list-templates",
      "list-topics",
      "list-webhooks",
    ],
  },
  sentry: {
    critic: [
      "find_organizations",
      "find_projects",
      "find_issues",
      "search_issues",
      "get_issue_details",
      "search_events",
      "search_issue_events",
    ],
    description:
      "Sentry error tracking, read-only: issues, events, stack traces, breadcrumbs, traces, session replays, releases, and performance data.",
    root: ["*"],
  },
  stripe: {
    critic: [
      "get_stripe_account_info",
      "list_available_accounts_or_orgs",
      "search_stripe_documentation",
      "stripe_api_details",
      "stripe_api_read",
      "stripe_api_search",
      "stripe_implementation_planner",
    ],
    description:
      "Stripe billing, read-only: customers, subscriptions, invoices, payments, refunds, disputes, products, and Stripe documentation search.",
    root: [
      "get_stripe_account_info",
      "list_available_accounts_or_orgs",
      "search_stripe_documentation",
      "stripe_api_details",
      "stripe_api_read",
      "stripe_api_search",
      "stripe_implementation_planner",
    ],
  },
  supermemory: {
    critic: [],
    description:
      "Supermemory: attended-session semantic recall over saved memories, documents, and spaces. It is unrelated to triage investigation memory, repository authority, and databases.",
    root: [
      "search_memory",
      "listDocuments",
      "getDocument",
      "listMemories",
      "listSpaces",
      "whoAmI",
      "add_memory",
    ],
  },
  vercel: {
    critic: [
      "search_vercel_documentation",
      "list_teams",
      "list_projects",
      "get_project",
      "list_deployments",
      "get_deployment",
      "get_deployment_build_logs",
      "get_runtime_logs",
      "get_runtime_errors",
      "get_web_analytics",
      "list_agent_run_projects",
      "list_agent_runs",
      "get_agent_run",
      "get_agent_run_trace",
      "get_access_to_vercel_url",
      "web_fetch_vercel_url",
      "list_toolbar_threads",
      "get_toolbar_thread",
    ],
    description:
      "Vercel platform: projects, deployments, build and runtime logs, runtime errors, web analytics, toolbar threads, deploys, and Vercel documentation search.",
    root: [
      "search_vercel_documentation",
      "list_teams",
      "list_projects",
      "get_project",
      "list_deployments",
      "get_deployment",
      "get_deployment_build_logs",
      "get_runtime_logs",
      "get_runtime_errors",
      "get_web_analytics",
      "list_agent_run_projects",
      "list_agent_runs",
      "get_agent_run",
      "get_agent_run_trace",
      "get_access_to_vercel_url",
      "web_fetch_vercel_url",
      "list_toolbar_threads",
      "get_toolbar_thread",
      "deploy_to_vercel",
      "change_toolbar_thread_resolve_status",
      "reply_to_toolbar_thread",
      "edit_toolbar_message",
      "add_toolbar_reaction",
    ],
  },
} as const;
